objects = main.o plate_locate.o plate_judge.o plate_detect.o \
		chars_segment.o chars_identify.o chars_recognise.o plate_recognize.o

cc = g++

main : $(objects)
	cc -o main $(objects)

main.o : 
plate_locate.o : plate_locate.h
plate_judge.o : plate_judge.h
plate_detect.o : plate_detect.h
chars_segment.o : chars_segment.h
chars_identify.o : chars_identify.h
chars_recognise.o : chars_recognise.h
plate_recognize.o : plate_recognize.h

.PHONY : clean
clean :
	-rm edit $(objects)